#!/bin/bash
GIT_PATH=$(which git)
if [[ "$GIT_PATH" = "" ]]; then
  echo -e "\033[31m Please install Git. \033[0m"
  exit $?
elif [[ "$GIT_PATH" = "/usr/local/bin/git" ]]; then
  echo -e "\033[31m Installed. \033[0m"
  exit $?
fi

# 确定操作系统
if [[ "$(uname)" = "Linux" ]]; then
  OS=0
elif [[ "$(uname)" = "Darwin" ]]; then
  OS=1
else
  echo "The bash doese not support $(uname) OS"
fi

# 检测 /usr/local/bin 目录
if [[ ! -d /usr/local/bin ]]; then
  mkdir /usr/local/bin
fi

# 修改 OriginGit参数
GIT_FILE="/usr/local/bin/git"
if [[ ! -f "$GIT_FILE" ]]; then
  touch "$GIT_FILE"
  chmod +x "$GIT_FILE"
  # 下载脚本写入执行文件 /usr/local/bin/git
  curl https://raw.githubusercontent.com/JeasonZuo/git-commit-template/develop/git > $GIT_FILE
  if [[ $OS == 0 ]]; then
    sed -i "s#OriginGit=/usr/bin/git#OriginGit=$GIT_PATH#g" $GIT_FILE
  elif [[ $OS == 1 ]];then
    sed -i "" "s#OriginGit=/usr/bin/git#OriginGit=$GIT_PATH#g" $GIT_FILE
  fi
  echo "Complete."
else
  echo -e "\033[31m The file $GIT_FILE existed. \033[0m"
fi

# 检查PATH
if [[ ":${PATH}:" != *":/usr/local/bin:"* ]]; then
  echo "`/user/local/bin` is not in your PATH. Please check you PATH."
fi